const {chromium}=require('playwright');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1512,height:1100},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765');
 await page.getByText('Recommended landed cost',{exact:true}).waitFor();
 await page.screenshot({path:path.join(root,'docs/dashboard.png'),fullPage:true});
 console.log('winner',await page.locator('.recommendation h2').innerText());
 await page.locator('#deadline_days').fill('1');await page.locator('#analyze-btn').click();await page.getByRole('heading',{name:'No award recommended'}).waitFor();
 console.log('no-award verified');
 await page.locator('#deadline_days').fill('21');await page.locator('#analyze-btn').click();await page.locator('.rec-score').waitFor();
 await page.locator('[data-edit="Q001"]').click();await page.locator('[name="unit_price"]').fill('160');await page.getByRole('button',{name:'Apply & compare'}).click();await page.locator('#quote-dialog').waitFor({state:'hidden'});
 console.log('quote edit verified');
 await page.locator('#save-btn').click();await page.locator('#save-title').fill('QA scenario');await page.getByRole('button',{name:'Save snapshot'}).click();await page.locator('#save-dialog').waitFor({state:'hidden'});
 await page.locator('[data-view="history"]').click();await page.getByText('QA scenario',{exact:true}).waitFor();await page.getByRole('button',{name:'Load decision'}).first().click();await page.locator('#compare').waitFor({state:'visible'});
 await page.locator('[data-view="scenarios"]').click();await page.locator('#sensitivity-btn').click();await page.locator('.scenario-card').first().waitFor();if(await page.locator('.scenario-card').count()!==6)throw Error('Expected 6 scenarios');
 await page.screenshot({path:path.join(root,'docs/scenarios.png'),fullPage:true});
 console.log('save/load/scenarios verified');
 await page.locator('[data-view="compare"]').click();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export comparison CSV'}).click();const download=await downloadPromise;console.log('download',download.suggestedFilename());
 page.once('dialog',d=>d.accept());await page.locator('#csv-file').setInputFiles(path.join(root,'data/sample_quotes.csv'));await page.getByText('Imported 10 quotes successfully.').waitFor();
 console.log('CSV import verified');
 await page.locator('#sku').selectOption('FLT-H100');await page.locator('#analyze-btn').click();await page.getByText('FLT-H100 · 1,000 required units',{exact:false}).waitFor();
 console.log('product switch verified');
 await page.locator('#sku').selectOption('BRG-6205');await page.locator('#analyze-btn').click();await page.locator('.rec-score').waitFor();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'docs/mobile.png'),fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);console.log({overflow,errors});if(overflow||errors.length)throw Error('UI errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
